name: TestWorkflow
on: push
jobs:
 my-job:
   runs-on: ubuntu-latest
   steps:
     - name: Do a basic task
       run: echo "Hello World!"
     - name: Copy code to runner environment
       run: actions/checkout@v3
   
